name             "ube"
maintainer       "Shodogg"
maintainer_email "admin@shodogg.com"
license          "Apache 2.0"
description      "Universal Backend"
long_description "U-N-I-V-E-R-S-A-L--B-A-C-K-E-N-D"
version          "1.0.0"
supports         "ubuntu"
depends          "aws"
depends          "mongodb"
depends          "redisio"